substitutions:
  backlight: "0.50"   # яркость подсветки на заставке 
  screensaver: "1min"  # задержка заставки
#   # ========== Гистерезис =============
#   heat_overrun: "0.5"          # нагревает выше + 0.5 от заданной
#   heat_deadband: "0.5"         # остывает на - 0.5 от заданной
#   # ===================================
  
esphome:
  name: home-thermostat
  on_boot:
#    - lambda: id(back_light).turn_on().set_brightness(1).perform(); // включаем подсветку на 100%
    - delay: 7s   # ждем 
    - lvgl.widget.hide: boot_screen   # закрываем экран загрузки
    - delay: 5s   # ждем
    - lambda: |-  
        id(thermostat_house).set_heat_deadband(id(heat_deadband) / 10);  // восстанавливаем значение гистерезиса термостата
        id(thermostat_house).set_heat_overrun(id(heat_overrun) / 10);  // восстанавливаем значение гистерезиса термостата
    - lambda: id(back_to_screensaver).execute();    // запускаем скрипт перехода на заставку
    - lvgl.arc.update:
        id: arc_therm
        value: !lambda return id(thermostat_house).target_temperature;
    - lvgl.spinbox.update:
        id: gist_down
        value: !lambda return id(heat_deadband);
    - lvgl.spinbox.update:
        id: gist_up
        value: !lambda return id(heat_overrun);
    - lvgl.spinbox.update:
        id: temp_correction
        value: !lambda return id(ntc_temp_correction) * 10;
    - lvgl.slider.update:
        id: slider_light
        value: !lambda return id(set_brghtness);

esp32:
  board: lolin32_lite
  framework:
    type: esp-idf

preferences:
  flash_write_interval: 10s

logger:

<<: !include lvgl\lvgl.yaml
<<: !include display\display.yaml
<<: !include sensors\sensors.yaml

climate: !include climate\climate.yaml
font: !include font\font.yaml

api:
  encryption:
    key: "hz7wz2DN+MedfQQw4kCZDnxYyQwdP6sVfHhrVzTK8Vs="
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: lbl_apistatus
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: lbl_apistatus
          
ota:
  - platform: esphome
    password: "3022eb295d8867a45620d4457b30fef0"

wifi:
  networks:
    - ssid: OpenWrt
      password: "9514210798"
    - ssid: Keenetic-Home
      password: "9994554500"
    - ssid: IoT_Office
      password: "9514210798"
  on_connect:
    then:
      - lvgl.widget.show: lbl_wifitatus

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "2BgdJnlx1D7T"

web_server:
  port: 80

udp:
captive_portal:

switch:
  # основное реле термостата
  - platform: gpio
    id: relay
    name: Relay 2
    pin: GPIO25
    on_turn_on:
      - lvgl.widget.show: lbl_heateron
    on_turn_off:
      - lvgl.widget.hide: lbl_heateron

output:
  # выход подсветки дисплея
  - platform: ledc
    pin: GPIO13
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: RESTORE_DEFAULT_ON
    # on_state:
    #   then:
    #     - delay: 1s
    #     - lvgl.slider.update:
    #         id: slider_light
    #         value: !lambda return (id(back_light).current_values.get_brightness() * 100);

text:
  - platform: lvgl
    id: state_text
    widget: lbl_state
    name: "Thermostat state text"
    mode: text 
    internal: true

image:
  - file: https://esphome.io/favicon-512x512.png
    id: boot_logo
    resize: 80x80
    type: RGB565
    transparency: chroma_key

  - id: my_background_image
    file: "img/img11.jpg"
    type: rgb565
    resize: 130x170  # Опционально: масштабирование при загрузке

  - id: time_background_image
    file: "img/img8.jpg"
    type: rgb565
    resize: 130x170  # Опционально: масштабирование при загрузке

button:
  - platform: restart
    id: restart_button
    name: Thermostat Restart 

time:
  - platform: sntp
    id: ntp_time
    timezone: Asia/Omsk
    servers:
      - 0.pool.ntp.org
      - 192.168.1.1
      - 2.openwrt.pool.ntp.org

    on_time_sync:
      then:
        - logger.log: "Synchronized system clock"
        - script.execute: time_update

    on_time:
      - seconds: 0,30
        then:
          lambda: |-
            if (id(ntp_time).now().is_valid()) {
              char str[17];
              auto currTime = id(ntp_time).now().timestamp;
              strftime(str, sizeof(str), "%H:%M", localtime(&currTime));
              lv_label_set_text(id(lbl_time), str);
            }

      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update

script:
  - id: time_update   # скрипт часов на заставке
    then:
      - lvgl.label.update:
          id: lvgl_clock_minute
          text:
            format: "%02d"
            args: [ 'id(ntp_time).now().minute' ]

      - lvgl.label.update:
          id: lvgl_clock_hour
          text:
            format: "%02d"
            args: [ 'id(ntp_time).now().hour' ]

      - lvgl.label.update:
          id: lvgl_clock_longdate
          text:
            format: "%02d.%02d.%04d"
            args: 
              - 'id(ntp_time).now().day_of_month'
              - 'id(ntp_time).now().month'
              - 'id(ntp_time).now().year'
          
  - id: back_to_screensaver    # Скрипт таймер перехода на заставку
    mode: restart
    then:
      - delay: ${screensaver}
      - lvgl.widget.hide: status_bar
      - lvgl.page.show: page_time
      - lambda: id(back_light).turn_on().set_brightness(${backlight}).perform();

globals:
  # память гистерезиса
  - id: heat_deadband
    type: float
    initial_value: "0.5"
    restore_value: true

  # память гистерезиса
  - id: heat_overrun
    type: float
    initial_value: "0.5"
    restore_value: true

  # память заданной основной яркости
  - id: set_brghtness
    type: int
    initial_value: '50'
    restore_value: true

  - id: ntc_temp_correction
    type: float
    initial_value: "0.0"
    restore_value: true

  - id: current_page
    type: int
    restore_value: no
    initial_value: '0'  # например, 0 = page_one, 1 = page_settings


